name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Playwright install
      run: npx playwright install --with-deps

    - name: Install MS Edge
      if: ${{ matrix.os == 'macos-latest' }} # MS Edge is not preinstalled on macOS runners.
      run: npx playwright install msedge

    - name: Run linting
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run tests
      run: npm test
      env:
        PWTEST_BOT_NAME: ${{ matrix.os }}

    - name: Upload blob report
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: blob-report-${{ matrix.os }}
        path: blob-report
        retention-days: 1

  merge-reports:
    permissions:
      pull-requests: write  # Post comments to the PR
      contents: read    # This is required for actions/checkout to succeed
    if: ${{ !cancelled() }}
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - uses: actions/checkout@v4
      name: Checkout GHA markdown reporter
      with:
        repository: microsoft/playwright
        path: playwright
        sparse-checkout: |
          packages/playwright-dashboard/src/

    - name: Download blob reports
      uses: actions/download-artifact@v4
      with:
        path: all-blob-reports
        pattern: blob-report-*
        merge-multiple: true
    - name: Merge into HTML Report
      run: npx playwright merge-reports all-blob-reports --reporter ./playwright/packages/playwright-dashboard/src/ghaMarkdownReporter.ts,html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: html-report--attempt-${{ github.run_attempt }}
        path: playwright-report
        retention-days: 7
